service:
  name: product-service

frameworkVersion: '2'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    PG_HOST: nodejs-aws-db.cydsgwcxyugb.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: cycle_store
    PG_USERNAME: postgres
    PG_PASSWORD: # password required

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
  postProduct:
    handler: handler.postProduct
    events:
      - http:
          path: products
          method: post
          cors: true
